project_id = "rnjkjzloyttcselzsoao"

[functions.generate-roadmap]
verify_jwt = false

[functions.check-in]
verify_jwt = false

[functions.adapt-roadmap]
verify_jwt = false

[functions.populate-resources]
verify_jwt = false

[functions.generate-module-quiz]
verify_jwt = false
